
= PATRONES: Connect 4
MÃSTER EN DESARROLLO DE SOFTWARE 2022
:toc-title: Index
:toc: none

:idprefix:
:idseparator: -
:imagesdir: images


== Vocabulary


[plantuml, DiagramaVocabulary, svg]
....

abstract Token
abstract Goal

Game *-d-> Board
Game *-d-> "2" Player
Game *-d-> Turn

Turn -> "2" Player

Player .> Board
Player *-> Goal
Player *--> "21" Token

Board .> Goal
Board *-> "6x7" Position
Board .> Token

Token -> Position
Token <|-d- RedToken
Token <|-d- YellowToken

Goal <|-d- Horizontal
Goal <|-d- Vertical
Goal <|-d- Diagonal

....


== InitialState

[plantuml, DiagramaInitialState, svg]
....

object Game
object Player1
object RedToken1
object RedTokenN
object Board
object Turn
object Player2
object YelowToken1
object YelowTokenN
object Position1x1
object PositionNxM
object Position6x7

Game *-> Turn
Game *-d--> Player1
Game *-d--> Player2
Game *-> Board

Turn -d-> Player1
Turn -d-> Player2

Board *-d-> Position1x1
Board *-d-> PositionNxM
Board *-d-> Position6x7

Player1 *--> RedToken1
Player1 *--> RedTokenN

Player2 *--> YelowToken1
Player2 *--> YelowTokenN

....

== FinalState

[plantuml, DiagramaFinalState, svg]
....

object Game
object Player1
object RedToken1
object RedTokenN
object Board
object Turn
object Player2
object YelowToken1
object YelowTokenN
object Position1x1
object Position1x2
object Position1x4
object PositionNxM

Game *--> Turn
Game *--> Player1
Game *--> Player2
Game *--> Board

Turn --> Player1
Turn --> Player2

Board *-u-> Position1x1
Board *-u-> Position1x2
Board *-u-> Position1x4
Board *-u-> PositionNxM

Player1 *--> RedToken1
Player1 *--> RedTokenN

Player2 *--> YelowToken1
Player2 *--> YelowTokenN

RedToken1 --> Position1x1
RedTokenN --> Position1x2

YelowToken1 --> Position1x4
YelowTokenN --> PositionNxM

....



== Instructions

[plantuml, DiagramaInstructions, svg]
....

class Connect4

....