
= PRUEBA: PLANT UML
MÁSTER EN DESARROLLO DE SOFTWARE 2022
:toc-title: Index
:toc: none

:idprefix:
:idseparator: -
:imagesdir: images




== 1. Imperative Grid

Dado este diagrma:
https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuU9oG331BAwYr8BKn18kg-2CpBGI3QNY_DAI32LDQwYuGdb6PawgWeQYXaPwQebB9b1FNdAgQqfwgePINduHIAc2hQsj0eOar1mWKCWiLj2eJ2tMHBSgDR6uX3YR82gnMrIU2f93iGTc0LXAHy48Q8ULIr5YETGW7GLJe4XnINu1C3XIyr8WuG9X0000

Escribe el correspondiente texto para la herramienta imperativeGrid:
https://github.com/USantaTecla-tech-dhtml/tool-grid/tree/master/0-imperativeGrid/v0.0


[
    While(
        Not(
            Equals(
                GetDistanceEdge("east"),
                GetDistanceEdge("south")
            )
        ),
        [
            Shift("south")
        ]
    ),
    While(
        Not(
            Equals(
                GetDistanceEdge("east"),
                GetDistanceEdge("west")
            )
        ),
        [
            Shift("east")
        ]
    ),
    Shift("west", 2),
    Draw("east", 5)
]


== 2. Álgebra de Boole

Escribe la expresión correspondiente a la salida "suma" del circuito sumador total de dos bits del apartado Algebra de Boole del tema Conocimiento.

=== Suma = A or B or Cin
=== Cout = (A x B) + Cin x (A or B)



== 3. Lenguaje de Signos

Propón un lenguaje de signos/símbolos, no hablado/escrito, que no sea el "semáforo" o el "policía de tráfico" y justifica tu respuesta.

El lenguaje de los abanicos: https://blog.fuertehoteles.com/wp-content/uploads/2013/08/lenguaje-abanico.jpg



== 4. Las Meninas

Modela con UML el cuadro de "Las Meninas de Velázquez" de tal forma que se observe qué diferencias existen con otros cuadros en los que el observador no se siente dentro de la escena (Pista: relaciones entre observador, personajes y posiciones)


=== Cuadro Normal

[plantuml, DiagramaVocabulary, svg]
....

object Law
object Ayuso
object AyusosBrother
object Piter
object Stalin
object ManuelaCarmena

object Innocence
object ProvenGuilty
object LaVerdad

Law -d-> Innocence
Law -d-> ProvenGuilty

Ayuso <-r-> AyusosBrother
Ayuso -u-> Innocence

AyusosBrother -u-> Innocence

Piter <-l-> Stalin
Piter <-r-> ManuelaCarmena
Piter -u-> "?" Innocence

Stalin -u-> ProvenGuilty

ManuelaCarmena -d-> LaVerdad

....


=== Cuadro Normal

[plantuml, DiagramaVocabulary, svg]
....

Painter .> Picture

Observer "n" .l.> Picture

Picture *-d-> Scene

Scene *-d-> "0..n" Character

....


=== Cuadro de las Meninas

En Las Meninas la escena del cuadro contiene a su vez un cuadro y se incluye al pintor como un personaje más.

[plantuml, DiagramaVocabulary, svg]
....

Painter .> Picture
Painter -|> Character

Observer "n" .l.> Picture
Observer "n" ---> ReflectedCharacterHypotheticalPosition

Picture *-d-> Scene

Scene *--> "12" Character
Scene *--> Picture

OtherPosition --|> Position
ReflectedCharacterHypotheticalPosition --|> Position

Character -> "10" OtherPosition
Character --> "2" ReflectedCharacterHypotheticalPosition

....




== 5. Triángulo de Pascal

Describe el triangulo de Tartaglia de forma recursiva:


=== Descripción del Triángulo de Pascal

[source, java]
----

// Para todo elemento <= fila:

class Triangulo {

    int[][] Triangulo(int n) {

        If(n = 1) {

            [1];

        } else {

            this.concat(
                this.Triangulo(n-1),
                concat(1, ultimaFila(Triangulo(n-1)), 1)
        }

    }

    private ultimaFila() {}

    private concat() {}
}

----


=== Descripción del Triángulo de Pascal

[source, java]
----

// Para todo elemento <= fila:

Triangulo(fila, elemento) {

    If(fila = 1) {
        1
    } else if (elemento = 1) {
        valorPosicion(fila-1, elemento)
    } else if (elemento = i) {
        valorPosicion(fila-1, elemento-1)
    } else {
        valorPosicion(fila-1, elemento-1) + valorPosicion(fila-1, elemento)
    }
}

----


=== Descripción del Triángulo de Pascal

[source, java]
----

// Para todo elemento <= fila:

valorPosicion(fila, elemento) {

    If(fila = 1) {
        1
    } else if (elemento = 1) {
        valorPosicion(fila-1, elemento)
    } else if (elemento = i) {
        valorPosicion(fila-1, elemento-1)
    } else {
        valorPosicion(fila-1, elemento-1) + valorPosicion(fila-1, elemento)
    }
}

----


=== Clase TrianguloPascal

[source, java]
----

public class TrianguloPascal {

    private int[] triangulo;

    public TrianculoPascal(dimension) {

         return this.dimension;
    }

    public construirTriangulo(int[] triangulo) {

        private int[] trianguloAmpliado;
        private int[] fila = this.triangulo[triangulo.lenght()];
        private int[] filaSiguiente;

        for(int i = 0, i < this.fila.lenght(), i++) {

            this.filaSiguiente[i] = this.fila[i-1] + this.fila[i]
        }

        return this.trianguloAmpliado = this.triangulo.append(this.filaSiguiente);

        

// 1)              1
// 2)            1   1
// 3)          1   2   1
// 4)        1   3   3   1
// 5)      1   4   6   4   1


lenght([[1], [1,1], [1,2,1], ...])

----