
= PRUEBA: PLANT UML
MÁSTER EN DESARROLLO DE SOFTWARE 2022
:toc-title: Index
:toc: none

:idprefix:
:idseparator: -
:imagesdir: images



== 1. Las Meninas

Modela con UML el cuadro de "Las Meninas de Velázquez" de tal forma que se observe qué diferencias existen con otros cuadros en los que el observador no se siente dentro de la escena (Pista: relaciones entre observador, personajes y posiciones)


[plantuml, DiagramaVocabulary, svg]
....

Painter .> Picture
Painter -|> Character

Observer "n" .l.> Picture
Observer "n" ---> ReflectedCharacterHypotheticalPosition

Picture *-d-> Scene

Scene *--> "12" Character
Scene *--> Picture

OtherPosition --|> Position
ReflectedCharacterHypotheticalPosition --|> Position

Character -> "10" OtherPosition
Character --> "2" ReflectedCharacterHypotheticalPosition

....



== 2. Puerta XOR

Dada la tabla de verdad (combinaciones de cierto y falso) de la "puerta" XOR (especificación en tabla verde de https://es.wikipedia.org/wiki/Puerta_XOR), escribe la expresión lógica de la salida (tercera columna) correspondiente a la entrada (primeras 2 columnas)



== 3. Corregir Diagrama

Comenta la posible incorrección del siguiente diagrama:

https://www.planttext.com/api/plantuml/svg/RP7D2eCm48Jl-nIBzxo0b6AXHOyzz5vM8n8RioM9s48Vlchyg_IKPUPRTeOapfFrRQC1I6lkxerwALC159gSmvDH3McWt7bBXSUWPcr3XYSajMJgqZ90WF7m4P8x8sOiFAkyBimJ2d6SJc6CHQia0N1Ub_t5wChsyOw36o4vV0x2Of_PaDxQSX3aujyKNzggD8hZ46I4_A9c_yWvs8vD0JQBGoE1F_Pc7ZkDKPTAUpSaNHj3KXhPVyKN


Diagrama de clases:
- Debería estar en inglés
- Humano (clase abstracta) no puede heredar de una clase no abstracta (Animal)

Diagrama de objetos: 
- Debería estar en inglés
- Entre objetos puede existir herencia
- No pueden existir objetos de clases abstractas (TioEugenio:Humano)

DUDA: Si "Humano" fuera una clase NO abstracta ¿podríamos tener en un mismo diagrama de objetos, a la vez, un objeto "TioEugenio:Humano" y un objeto "TioEugenio:Granjero"? (sin que haya relación de herencia entre objetos, por supuesto)



== 4. Modelo del Máster

Realiza un modelo (... esencial ... aproximadamente, no más de 20 tipos de entidad y algún diagrama de actividad o estados para algún proceso) de este mismo master de Programación y Diseño del Software.

[plantuml, DiagramaClasesMaster, svg]
....

Master *-down-> Teacher
Master *-down-> Content
Content *-down-> "54" Unit

Viewer <|-- Critic
Viewer <|-- Artist

Viewer "0..n" -r-> Master

Unit *-down-> "0..*" Practice

Practice <|-- Exercise
Practice <|-- Test

Critic -> Artist

Artist -> Exercise

....



== 5. Unidades Patrones y Conocimiento

Relaciona, con aproximadamente 50 palabras, las unidades de Patrones y Conocimiento vistos anteriormente.


El *Conocimiento* es la compresión de una realidad *Compleja*, mediante la busqueda de *Patrones* 



[plantuml, DiagramaVocabulary, svg]
....

class Patrones
class Conocimiento
class Datos
class Informacion
class Objetos
class Clases
class Relacion
class Jerarquia
class JerarquiaDeComposicion
class JerarquiaDeClasificacion
class JerarquiaDeAsociacion
class JerarquiaDeClasificacion
class Conjunto
class Compresión

....