
== 1. Diagrama de Clases

Modela un diagrama de clases que relacione las siguientes palabras clave: software, hardware, firmware, dataware, middleware, peopleware.


[plantuml, DiagramaDeClases, svg]
....

Hardware *--> Firmware
Hardware o--> Middleware
Hardware o--> Dataware

Software <|-u- Firmware
Software <|-u- Middleware
Software <|-u- Dataware

Middleware -u-> Firmware
Firmware -d-> Dataware
Middleware -> Dataware

Peopleware <|-- Developer
Peopleware <|-- User

Developer --> Hardware
User --> Hardware

....



== 2. Definición de Software de la IEEE

Comenta en qué medida es correcta la definición de software de la IEEE en el estándar 729: "Es el conjunto de los programas de cómputo, procedimientos, reglas, documentación y datos asociados, que forman parte de las operaciones de un sistema de computación"

- Es aceptable en la relación que define entre Software y Hardware (entendiendo que cuando habla de "sistema de computación" habla de este segundo). Sin embargo obvia toda relación con el "Peopleware"



== 3. CRUD Hoja de Cálculo

Desarrolla por qué una aplicación de hoja de cálculo es un gestor (altas, bajas, modificaciones y consultas) de un sistema de información

Porque las tareas básicas que realiza toda aplicación de hoja de cálculo son:

- Escribir, borrar, cambiar y mostrar/consultar un valor en una celda.
- Escribir, borrar, cambiar y mostrar/consultar una operación o función que implique a una o varias celdas.



== 4. Lineas de código de Photoshop

A partir de este diagrama, https://www.informationisbeautiful.net/visualizations/million-lines-of-code/ calcula aproximadamente el incremento medio de líneas diarias en photoshop desde la versión 1.0 de 1990 hasta la versión 6.0 de 2020

- Photoshop 1.0 (1990) -> 100.000 lineas
- Photoshop 6.0 (2020) -> 4.500.000 lineas

- dias = (2020 - 1990) * 365 = 10.950
- media = (4.500.000 - 100.000) / 10.950 = 402 lineas diarias



== 5. Contenido del tema del Software

Resume el contenido del tema del Software con aproximadamente 50 palabras

???

